(() => {
  const invoke = window.__TAURI__.core.invoke;
  const KEY = "wint.git.context.v2";
  const saved = (() => { try { return JSON.parse(localStorage.getItem(KEY) || "{}"); } catch { return {}; } })();
  const S = { root:null, body:null, path:saved.path||"", name:saved.name||"Repository", repositories:Array.isArray(saved.repositories)?saved.repositories:[], data:null, busy:false, error:"", notice:"", selected:"", excluded:new Set(), openPoint:"", branchMenu:false, help:false, commitView:null, filesScroll:0, loadToken:0, technical:Boolean(saved.technical) };
  const esc = (v="") => String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const icon = n => `<span class="ms">${n}</span>`;
  const rel = t => { const n=Math.max(0,Date.now()/1000-t); return n<60?"just now":n<3600?`${Math.floor(n/60)} minutes ago`:n<86400?`${Math.floor(n/3600)} hours ago`:`${Math.floor(n/86400)} days ago`; };
  const remember = () => { try { localStorage.setItem(KEY,JSON.stringify({path:S.path,name:S.name,repositories:S.repositories,technical:S.technical})); } catch {} };

  function mount(host) {
    S.root=host;
    host.innerHTML=`<header class="tool-head git-head"><button class="btn back tool-back" data-open-tool="overview">${icon("arrow_back")}Back</button><span class="tool-plate">${icon("bookmark_added")}</span><span class="tool-title"><strong data-git-title>Version history</strong><small data-git-subtitle>record versions on this computer and upload them when ready</small></span>${window.wintMaturity?.badge("git")??""}<button class="tool-popout" data-popout-tool="git">${icon("open_in_new")}Pop out</button><button class="tool-pin" data-pin-tool="git">${icon("push_pin")}Pin to dock</button><button class="tool-close" data-open-tool="overview">${icon("close")}</button></header><div class="git-tool-body"></div>`;
    S.body=host.querySelector(".git-tool-body"); host.addEventListener("click",helpClick); host.addEventListener("click",branchClick); host.addEventListener("click",commitClick); host.addEventListener("click",click); host.addEventListener("submit",submit); render();
  }
  function setRepositories(rows){S.repositories=Array.isArray(rows)?rows:[];remember();if(!S.path)render()}
  function scheduleLoad(){if(!S.path)return;const token=++S.loadToken;requestAnimationFrame(()=>requestAnimationFrame(()=>{if(token===S.loadToken&&S.path)load(token)}))}
  function opened(){render();if(S.path&&!S.data&&!S.busy)scheduleLoad()}
  function open(path,name){S.loadToken++;S.path=path||"";S.name=name||path?.split(/[\\/]/).pop()||"Repository";S.data=null;S.selected="";S.excluded.clear();S.error="";S.notice="";remember();render();if(S.path)scheduleLoad()}
  async function load(token=S.loadToken){if(!S.path)return;const path=S.path;S.busy=true;S.error="";render();try{const data=await invoke("git_workspace",{path});if(token!==S.loadToken||path!==S.path)return;S.data=data;const fs=S.data.info.changed||[],firstConflict=fs.find(f=>f.status==="conflict");if(firstConflict)S.selected=firstConflict.path;else if(!fs.some(f=>f.path===S.selected))S.selected=fs[0]?.path||""}catch(e){if(token===S.loadToken&&path===S.path)S.error=String(e)}finally{if(token===S.loadToken&&path===S.path){S.busy=false;render()}}}
  async function act(action,value=""){if(S.busy)return;S.busy=true;S.notice="Working…";render();try{const r=await invoke("git_action",{request:{path:S.path,action,value,amend:false}});S.notice=r.output||"Done";if(!r.ok)S.error=S.notice;else S.error="";await load()}catch(e){S.error=String(e);S.busy=false;render()}}
  async function savePoint(message){if(S.busy)return;S.busy=true;S.error="";S.notice=S.technical?"Creating commit…":"Recording this version…";render();try{for(const f of S.data.info.changed||[])await invoke("git_action",{request:{path:S.path,action:S.excluded.has(f.path)?"unstage":"stage",value:f.path,amend:false}});const r=await invoke("git_action",{request:{path:S.path,action:"commit",value:message,amend:false}});if(!r.ok)throw new Error(r.output);S.notice=S.technical?"Commit created locally; it has not been pushed yet.":"Version recorded on this computer. It has not been uploaded anywhere else yet.";S.excluded.clear();await load()}catch(e){S.error=String(e);S.busy=false;render()}}
  async function showCommit(hash){if(S.busy)return;S.busy=true;S.commitView={hash,title:S.data?.history?.find(c=>c.hash===hash)?.subject||hash,text:"",loading:true};render();try{const result=await invoke("git_action",{request:{path:S.path,action:"show_commit",value:hash,amend:false}});if(!result.ok)throw new Error(result.output);S.commitView={...S.commitView,text:result.output,loading:false}}catch(e){S.commitView={...S.commitView,text:String(e),loading:false,error:true}}finally{S.busy=false;render()}}
  function fileDiff(path){if(!S.data?.diff||!path)return "";const marker=`diff --git a/${path} b/${path}`,start=S.data.diff.indexOf(marker);if(start<0)return "No textual preview for this file.";const next=S.data.diff.indexOf("\ndiff --git ",start+1);return S.data.diff.slice(start,next<0?undefined:next)}
  function diffHtml(text){return esc(text).split("\n").map((line,i)=>`<div class="sp-diff-line ${line[0]==="+"&&!line.startsWith("+++")?"add":line[0]==="-"&&!line.startsWith("---")?"del":line.startsWith("@@")?"hunk":""}"><i>${i+1}</i><code>${line||" "}</code></div>`).join("")}
  function conflictRows(mine,theirs){const a=String(mine).split("\n").slice(0,500),b=String(theirs).split("\n").slice(0,500),n=a.length,m=b.length,dp=Array.from({length:n+1},()=>new Uint16Array(m+1));for(let i=n-1;i>=0;i--)for(let j=m-1;j>=0;j--)dp[i][j]=a[i]===b[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);const rows=[];let i=0,j=0;while(i<n||j<m){if(i<n&&j<m&&a[i]===b[j]){rows.push([i++,j++,a[i-1],b[j-1],false]);continue}if(j>=m||(i<n&&dp[i+1][j]>=dp[i][j+1]))rows.push([i++,null,a[i-1],"",true]);else rows.push([null,j++,"",b[j-1],true])}return rows}
  function conflictPanel(c,t){return `<div class="conflict-tool"><div class="conflict-explain">${icon("compare_arrows")}<span><strong>${t?"Resolve this merge conflict":"You both changed this file at the same time. What should we do?"}</strong><small>${t?"Both sides changed overlapping lines, so Git could not merge them automatically. Choose one complete version to stage.":"You changed some of the same parts, so it isn’t safe to keep both. Compare them below, then choose the complete version you want."}</small></span></div><div class="conflict-head"><section><span><strong>${t?"Our version":"My version"}</strong><small>${t?"Keep ours and stage":"Keep all of my changes"}</small></span><button data-git-resolve="mine">${icon("person")} ${t?"Use ours":"Keep my version"}</button></section><section><span><strong>${t?"Their version":"Their version"}</strong><small>${t?"Keep theirs and stage":"Keep all of their changes"}</small></span><button data-git-resolve="theirs">${icon("group")} ${t?"Use theirs":"Keep their version"}</button></section></div><div class="conflict-compare">${conflictRows(c.mine,c.theirs).map(([an,bn,av,bv,changed])=>`<div class="conflict-row${changed?" changed":""}"><code><i>${an==null?"":an+1}</i><span>${esc(av)||" "}</span></code><code><i>${bn==null?"":bn+1}</i><span>${esc(bv)||" "}</span></code></div>`).join("")}</div></div>`}
  function picker(){const tech=S.technical;return `<div class="git-picker"><header>${icon("bookmark_added")}<div><h2>${tech?"Choose a repository":"Choose a project"}</h2><p>${tech?"Git repositories found during the latest scan.":"Projects whose versions WinT can manage for you."}</p></div><button class="git-terms-toggle" data-git-terms>${icon(tech?"toggle_on":"toggle_off")}${tech?"Use simple words":"Use Git terms"}</button><b>${S.repositories.length}</b></header><div class="git-picker-list">${S.repositories.length?S.repositories.map(r=>`<button data-git-open="${esc(r.path)}" data-git-name="${esc(r.name)}"><span class="git-picker-icon">${icon("folder_code")}</span><span><strong>${esc(r.name)}</strong><small>${esc(r.path)}</small></span><span class="git-picker-state"><b>${icon("fork_right")}${tech?`branch ${esc(r.branch||"detached")}`:`working on ${esc(r.branch||"default")}`}</b><small>${r.dirty?`${r.changed} ${tech?"uncommitted changes":"file changes not recorded"}`:r.ahead?`${r.ahead} ${tech?"commits ahead":"versions only on this computer"}`:tech?"working tree clean":"no pending file changes"}${r.behind?` · ${r.behind} ${tech?"behind":"from teammates"}`:""}</small></span>${icon("chevron_right")}</button>`).join(""):`<div class="git-picker-none">${icon("search_off")}<h3>${tech?"No Git repositories found":"No versioned projects found"}</h3><p>Scan a folder containing a project, then return here.</p></div>`}</div></div>`}
  function oldWorkspace(){
    const d=S.data,g=d.info,files=g.changed||[],included=files.filter(f=>!S.excluded.has(f.path)),clean=!files.length;
    return `<div class="sp-shell"><div class="sp-repo-bar"><button data-git-choose>${icon("folder_open")}<span><strong>${esc(S.name)}</strong><small>${esc(S.path)}</small></span>${icon("unfold_more")}</button><span>${icon("fork_right")}${esc(g.branch||"detached")}</span><i></i><button data-git-advanced>${icon(S.advanced?"toggle_on":"toggle_off")}Git commands</button></div>${S.error?`<div class="git-alert">${icon("error")}${esc(S.error)}</div>`:""}
      <div class="sp-layout"><main><section class="sp-hero"><div><span class="sp-safe">${icon(clean?"check_circle":"verified")}</span><span><h2>${clean?"Saved. Your work is safe on this computer.":"Your work is safe on this computer."}</h2><p>${clean?"Back it up when you’re ready and the rest of the team will see it.":`${included.length} of ${files.length} changed files will go into the next save point.`}</p></span></div><form class="sp-save"><input name="message" placeholder="What did you change? e.g. Fixed the login button" required><button ${included.length?"":"disabled"}>${icon("bookmark_add")}Save ${included.length||"files"}</button></form></section>
      <section class="sp-changes"><header>${icon("folder_open")}<strong>What you changed</strong><small>All included files go into the next save point</small><i></i><button data-git-discard-all>${icon("undo")}Throw away all changes</button></header><div class="sp-files">${files.map(f=>`<button class="${f.path===S.selected?"on":""}${S.excluded.has(f.path)?" excluded":""}" data-git-file="${esc(f.path)}"><span>${icon(f.status==="untracked"?"note_add":"edit")}</span><span><strong>${esc(f.path.split(/[\\/]/).pop())}<b>${f.status==="untracked"?"New file":f.status==="conflict"?"Conflict":"Edited"}</b></strong><small>${esc(f.path)}</small></span><em data-git-skip="${esc(f.path)}">${icon(S.excluded.has(f.path)?"add_circle":"do_not_disturb_on")}${S.excluded.has(f.path)?"Include":"Leave out"}</em></button>`).join("")||`<div class="git-clean">${icon("task_alt")}Nothing has changed since your last save point.</div>`}</div><div class="sp-diff"><header>${icon("visibility")}Changes in ${esc(S.selected||"selected file")}<i></i><small><b>added</b><b>removed</b></small></header><div>${diffHtml(fileDiff(S.selected))}</div></div></section></main>
      <aside><section class="sp-team"><header>${icon("group")}<strong>${g.behind?`${g.behind} change${g.behind===1?"":"s"} from your team waiting`:"You’re up to date with your team"}</strong></header>${(d.incoming||[]).length?`<div class="sp-team-items">${d.incoming.slice(0,3).map(c=>`<p><i>${esc(c.author.split(/\s+/).map(x=>x[0]).join("").slice(0,2))}</i><span><strong>${esc(c.subject)}</strong><small>${esc(c.author)} · ${rel(c.timestamp)}</small></span></p>`).join("")}</div>`:`<p>No incoming changes are waiting on the tracked branch.</p>`}<div><button data-git-act="pull" ${g.behind?"":"disabled"}>${icon("download")}Get their changes</button><button data-git-act="push" class="primary" ${g.ahead?"":"disabled"}>${icon("cloud_upload")}Back up ${g.ahead||""}</button></div></section>
      <section class="sp-points"><header>${icon("history")}<strong>Your save points</strong><small>${d.history.length}</small></header><div>${d.history.map((c,i)=>`<article class="${S.openPoint===c.hash?"open":""}"><button data-git-point="${esc(c.hash)}"><i></i><span><strong>${esc(c.subject)}</strong><small>${esc(c.author)} · ${rel(c.timestamp)}${i<g.ahead?" · only on this PC":" · backed up"}</small></span></button>${S.openPoint===c.hash?`<footer><button data-git-see="${esc(c.hash)}">${icon("visibility")}See changes</button><button data-git-restore="${esc(c.hash)}">${icon("restore")}Go back to this</button></footer>`:""}</article>`).join("")||`<p>No save points yet.</p>`}</div></section>${S.advanced?`<section class="sp-advanced"><header>${icon("terminal")}Git commands</header><code>branch ${esc(g.branch)} · ${g.ahead} ahead · ${g.behind} behind<br>remote ${esc(g.remote||"none")}<br>${esc(S.notice||"Ready")}</code><div><button data-git-act="fetch">fetch</button><button data-git-act="stash">stash</button></div></section>`:""}</aside></div></div>`
  }
  function workspace(){
    const d=S.data,g=d.info,files=g.changed||[],included=files.filter(f=>!S.excluded.has(f.path)),clean=!files.length,t=S.technical,conflict=(d.conflicts||[]).find(c=>c.path===S.selected),connected=Boolean(g.remote&&g.upstream);
    const heroTitle=t?(clean?"Working tree clean.":"Uncommitted changes in the working tree."):!clean?"These file changes only exist in this working folder.":g.ahead?`${g.ahead} recorded ${g.ahead===1?"version exists":"versions exist"} only on this computer.`:connected?"Nothing is waiting to be recorded or uploaded.":"No file changes are waiting. This project is not connected to anywhere you can upload it.";
    const heroText=t?(!clean?`${included.length} of ${files.length} files will be staged and committed.`:g.ahead?`HEAD is ${g.ahead} commit${g.ahead===1?"":"s"} ahead of its upstream. These commits have not been pushed.`:connected?"The working tree is clean and HEAD is not ahead of upstream.":"The working tree is clean, but no upstream remote is configured."):!clean?"They have not been recorded as a version and have not been uploaded anywhere else.":g.ahead?"They are recorded in the version history on this computer, but have not been uploaded anywhere else.":connected?"Recorded versions have been uploaded to the connected server. This does not guarantee a separate backup.":"Recorded versions exist only on this computer until you connect this project to somewhere else.";
    const fileState=f=>t?(f.status==="untracked"?"Untracked":f.status==="conflict"?"Conflicted":f.status?.[0]!=="."?"Staged":"Modified"):(f.status==="untracked"?"New file":f.status==="conflict"?"Needs attention":"Changed");
    return `<div class="sp-shell"><div class="sp-repo-bar"><button data-git-choose>${icon("folder_open")}<span><strong>${esc(S.name)}</strong><small>${esc(S.path)}</small></span>${icon("unfold_more")}</button><div class="git-branch-picker"><button data-git-branches>${icon("fork_right")}<span><small>${t?"Branch":"Working on"}</small><strong>${esc(g.branch||"detached")}</strong></span>${icon("expand_more")}</button>${S.branchMenu?`<div class="git-branch-menu"><header><strong>${t?"Checkout branch":"Open another line of work"}</strong><small>${t?"Local branches":"Your project’s available work areas"}</small></header>${g.branches.map(b=>`<button data-git-checkout="${esc(b)}" class="${b===g.branch?"on":""}">${icon(b===g.branch?"radio_button_checked":"radio_button_unchecked")}<span><strong>${esc(b)}</strong><small>${b===g.branch?(t?"HEAD":"open now"):(t?"git checkout":"switch to this")}</small></span></button>`).join("")}</div>`:""}</div><i></i><button class="git-terms-toggle" data-git-terms>${icon(t?"toggle_on":"toggle_off")}${t?"Use simple words":"Use Git terms"}</button></div>${S.error?`<div class="git-alert">${icon("error")}${esc(S.error)}</div>`:""}
      <div class="sp-layout"><main><section class="sp-hero"><div><span class="sp-safe${!clean||g.ahead||!connected?" local-only":""}">${icon(!clean?"edit_note":g.ahead||!connected?"cloud_off":"cloud_done")}</span><span><h2>${heroTitle}</h2><p>${heroText}</p></span></div><form class="sp-save"><input name="message" placeholder="${t?"Commit message":"Describe this version, e.g. Fixed the login button"}" required><button ${included.length?"":"disabled"}>${icon("bookmark_add")}${t?`Commit ${included.length}`:`Record version${included.length?` · ${included.length}`:""}`}</button></form></section>
      <section class="sp-changes"><header>${icon("folder_open")}<strong>${t?"Working tree changes":"Your changed files"}</strong><small>${t?"Included files will be staged before commit":"Choose what belongs in the version you save"}</small><i></i><button data-git-discard-all>${icon("undo")}${t?"Discard unstaged changes":"Undo all file changes"}</button></header><div class="sp-files">${files.map(f=>`<button class="${f.path===S.selected?"on":""}${S.excluded.has(f.path)?" excluded":""}" data-git-file="${esc(f.path)}"><span>${icon(f.status==="untracked"?"note_add":f.status==="conflict"?"warning":"edit")}</span><span><strong>${esc(f.path.split(/[\\/]/).pop())}<b>${fileState(f)}</b></strong><small>${esc(f.path)}</small></span>${f.status==="conflict"?`<em class="needs-resolution">${icon("compare_arrows")}${t?"Resolve":"Choose a version"}</em>`:`<em data-git-skip="${esc(f.path)}">${icon(S.excluded.has(f.path)?"add_circle":"do_not_disturb_on")}${S.excluded.has(f.path)?(t?"Stage":"Add to version"):(t?"Unstage":"Don’t save this")}</em>`}</button>`).join("")||`<div class="git-clean">${icon("task_alt")}${t?"No changes in the working tree.":"You haven’t changed any files since the last saved version."}</div>`}</div><div class="sp-diff"><header>${icon(conflict?"compare_arrows":"visibility")}${conflict?(t?"Merge conflict in":"Choose a version for"):(t?"Diff for":"Changes inside")} ${esc(S.selected||"selected file")}<i></i>${conflict?"":`<small><b>${t?"additions":"added"}</b><b>${t?"deletions":"removed"}</b></small>`}</header><div>${conflict?conflictPanel(conflict,t):diffHtml(fileDiff(S.selected))}</div></div></section></main>
      <aside><section class="sp-team"><header>${icon("group")}<strong>${g.behind?(t?`${g.behind} upstream commit${g.behind===1?"":"s"}`:`${g.behind} saved version${g.behind===1?"":"s"} from your teammates`):(t?"Up to date with upstream":"You have all your teammates’ work")}</strong></header>${(d.incoming||[]).length?`<div class="sp-team-items">${d.incoming.slice(0,3).map(c=>`<p><i>${esc(c.author.split(/\s+/).map(x=>x[0]).join("").slice(0,2))}</i><span><strong>${esc(c.subject)}</strong><small>${esc(c.author)} · ${rel(c.timestamp)}</small></span></p>`).join("")}</div>`:`<p>${t?"HEAD is not behind its upstream branch.":"There is nothing new to download from your teammates."}</p>`}<div><button data-git-act="pull" ${g.behind?"":"disabled"}>${icon("download")}${t?"Pull":"Get teammates’ work"}</button><button data-git-act="push" class="primary" ${g.ahead?"":"disabled"}>${icon("cloud_upload")}${t?`Push ${g.ahead||""}`:`Share ${g.ahead||""} ${g.ahead===1?"version":"versions"}`}</button></div></section>
      <section class="sp-points"><header>${icon("history")}<strong>${t?"Commit history":"Recorded versions"}</strong><small>${d.history.length}</small></header><div>${d.history.map((c,i)=>`<article class="${S.openPoint===c.hash?"open":""}"><button data-git-point="${esc(c.hash)}"><i></i><span><strong>${esc(c.subject)}</strong><small>${esc(c.author)} · ${rel(c.timestamp)}${i<g.ahead?(t?" · ahead of upstream":" · only on this computer"):(t?" · reachable from upstream":" · uploaded to the remote")}</small></span></button>${S.openPoint===c.hash?`<footer><button data-git-see="${esc(c.hash)}">${icon("visibility")}${t?"Show commit":"See what changed"}</button><button data-git-restore="${esc(c.hash)}">${icon("restore")}${t?"Hard reset here":"Restore this version"}</button></footer>`:""}</article>`).join("")||`<p>${t?"No commits yet.":"You haven’t recorded a version yet."}</p>`}</div></section>${t?`<section class="sp-advanced"><header>${icon("terminal")}Repository status</header><code>branch ${esc(g.branch)} · ${g.ahead} ahead · ${g.behind} behind<br>remote ${esc(g.remote||"none")}<br>${esc(S.notice||"Ready")}</code><div><button data-git-act="fetch">Fetch</button><button data-git-act="stash">Stash</button></div></section>`:""}</aside></div></div>`;
  }
  function howItWorks(){
    const t=S.technical,w=(simple,git)=>t?git:simple,chip=git=>`<code class="hw-chip">${git}</code>`;
    const files=rows=>`<div class="hw-files">${rows.map(([i,n,s])=>`<p>${icon(i)}<span><b>${n}</b><small>${s}</small></span></p>`).join("")}</div>`;
    const timeline=rows=>`<div class="hw-timeline">${rows.map(([who,title,when,state],i)=>`<p><i class="${i<2?"hot":""}"></i>${who?`<em>${who}</em>`:""}<span><small class="hw-message-label">${t?"Commit message":"Version description"}</small><b>${title}</b><small>${when} · ${state}</small></span></p>`).join("")}</div>`;
    const actions=[["bookmark_add",w("Record a version","Commit"),w("Save the folder exactly as it is now, with one line about what changed.","Create a commit from the staged changes."),"git commit"],["cloud_upload",w("Upload to the team","Push"),w("Upload recorded versions so teammates can see and download them.","Push local commits to the upstream branch."),"git push"],["download",w("Get the team’s work","Pull"),w("Bring in versions your teammates uploaded.","Fetch and integrate upstream commits."),"git pull"],["restore",w("Go back in time","Restore"),w("Return files to an earlier recorded version.","Restore files from an earlier commit."),"git restore"]];
    const faqs=t?[["Do I need to be online?","Only for fetch, pull, and push. The working tree, commits, and history are available offline."],["What happens during a conflict?","Git pauses the merge. WinT shows both files side by side and asks which complete version to keep."],["How often should I commit?","Whenever you reach a useful, understandable step. Small commits are easier to review and restore."],["Are local commits backed up?","No. Unpushed commits exist only on this computer, and a remote is not necessarily an independent backup."]]:[["Do I need to be online?","Only to upload work or get the team’s work. Editing and recording versions work without a connection."],["Can I overwrite someone’s work?","If you changed the same part, WinT pauses, shows both versions side by side, and asks which one to keep."],["How often should I record a version?","Whenever something useful works. Recording often makes mistakes much easier to undo."],["Is a recorded version backed up?","No. It remains only on this computer until uploaded, and an uploaded copy is not guaranteed to be a separate backup."]];
    return `<div class="git-how-page hw-design"><div class="hw-page-head"><button data-git-help>${icon("arrow_back")}${w("Back to versions","Back to repository")}</button><span>${icon("history")}<i><h2>${w("How versions work","How Git works")}</h2><p>${w("A five-minute tour. No jargon, nothing to memorise.","Working trees, commits, remotes, and collaboration.")}</p></i></span><button class="git-terms-toggle" data-git-terms>${icon(t?"toggle_on":"toggle_off")}${t?"Use simple words":"Show the real Git names"}</button></div>
      <section class="hw-intro"><h3>${w("The one-sentence version","The short version")}</h3><p>${w("You work in a folder on your own computer. Every so often you record a version — a copy of the whole folder exactly as it is right now, that you can come back to. When you’re happy, you upload your versions to the team’s copy so teammates can get them.","You edit a working tree, stage changes, and commit them on a branch. Push commits to the upstream remote and pull commits created by collaborators.")}</p></section>
      <section class="hw-stage"><div class="hw-grid"><article class="hw-machine you"><header>${icon("computer")}<strong>${w("Your computer","Your working copy")}</strong><em>${w("you","local")}</em></header><div class="hw-edit-box"><b>${icon("edit_document")}${w("Today’s edits, not recorded yet","Uncommitted working-tree changes")}</b>${files([["edit","src/stream/dispatcher.ts",w("changed","modified")],["note_add","src/stream/backpressure.ts",w("new","untracked")],["note_add","docs/streaming.md",w("new","untracked")]])}<small>${w("Nobody else can see these changes yet.","These changes are neither committed nor pushed.")}</small></div><div class="hw-step">${icon("south")}<b>${w("Step 1 — record a version","Step 1 — commit")}</b>${chip("git commit")}</div><div class="hw-history"><header>${icon("history")}<b>${w("Your versions, newest first","Local commit history")}</b></header>${timeline([["",w("The app now waits longer before trying again","Increase retry delay"),"12 min ago",w("only on your computer","unpushed")],["",w("Made sure it handles a big rush of traffic","Add load test"),"1 hour ago",w("only on your computer","unpushed")],["",w("Logs identify their request","Add trace IDs"),"yesterday",w("uploaded","upstream")],["",w("Last checks before release","Release candidate"),"2 days ago",w("uploaded","upstream")]])}</div><div class="hw-tip">${icon("lightbulb")}<span><b>${w("Earlier versions stay available","Commits remain in history")}</b><small>${w("If something breaks, choose an earlier version and recover what worked.","Restore a file from an earlier commit when needed.")}</small></span></div></article>
        <div class="hw-transfer"><span><b>${w("Step 2 — upload","Step 2 — push")}</b>${chip("git push")}</span><div class="hw-line out">${icon("east")}</div><div class="hw-line in">${icon("west")}</div><span><b>${w("Step 4 — get theirs","Step 4 — pull")}</b>${chip("git pull")}</span></div>
        <div class="hw-right"><article class="hw-machine shared"><header>${icon("cloud")}<strong>${w("The team’s copy","The remote repository")}</strong><em>${w("everyone","remote")}</em></header><p class="hw-copy">${w("One shared copy of the project that nobody edits directly. Everyone uploads versions here, and they join one shared history. It lets the team exchange work; it is not guaranteed to be a separate backup.","The upstream remote receives pushed commits and exposes them to collaborators. A remote is not necessarily an independent backup.")}</p><div class="hw-history"><header>${icon("inventory_2")}<b>${w("One shared history — everyone’s work in one line","Shared upstream history")}</b></header>${timeline([["JH",w("Logs identify their request","Add trace IDs"),"yesterday",w("you","pushed")],["TM",w("Clearer port error message","Improve port error"),"yesterday",w("teammate","pushed")],["BR",w("Last checks before release","Release candidate"),"2 days ago",w("build robot","pushed")],["TM",w("Updated a library for security","Bump dependency"),"3 days ago",w("teammate","pushed")]])}</div></article><div class="hw-team-step"><span><b>${w("Step 3 — they do the same thing","Step 3 — collaborators push and pull")}</b><small>${w("Their computer, their edits, and the same team copy in the middle.","Each collaborator has an independent working copy and branch.")}</small></span>${icon("swap_vert")}</div><article class="hw-machine teammate"><header>${icon("computer")}<strong>${w("Your teammate’s computer","A collaborator’s working copy")}</strong><em>${w("teammate","local")}</em></header><div class="hw-edit-box"><b>${icon("edit_document")}${w("Their edits, not recorded yet","Their working-tree changes")}</b>${files([["edit","src/errors/report.ts",w("changed","modified")],["edit","package.json",w("changed","modified")]])}</div><p class="hw-copy">${w("They record versions, upload them, and get yours. Both of you add to the same history.","They commit locally, push to upstream, and pull your commits.")}</p></article></div></div></section>
      <section class="git-how-section hw-below"><h3>${w("Four things you’ll actually do","Four core Git operations")}</h3><div class="git-how-actions">${actions.map(a=>`<article>${icon(a[0])}<strong>${a[1]}</strong><p>${a[2]}</p>${chip(a[3])}</article>`).join("")}</div></section><section class="git-how-section hw-below"><h3>${w("Questions people ask on day one","Common questions")}</h3><div class="git-how-faqs">${faqs.map(q=>`<article>${icon("help")}<span><strong>${q[0]}</strong><p>${q[1]}</p></span></article>`).join("")}</div></section><div class="git-how-ready hw-below">${icon("history")}<span><strong>${w("That’s it — you’re ready","Ready to use Git")}</strong><small>${w("Open Versions, describe what changed, and record your first version.","Stage your changes, create a commit, and push when ready.")}</small></span><button data-git-help>${icon("arrow_forward")}${S.path?w("Go to versions","Go to repository"):w("Choose a project","Choose a repository")}</button></div></div>`;
  }
  function simplifiedHowItWorks(){
    const t=S.technical,word=(simple,git)=>t?git:simple;
    const actions=[
      ["bookmark_add",word("Record a version","Commit"),word("Take a named snapshot of your project as it is now. Do this whenever something works.","Create a commit from the staged changes."),"git commit"],
      ["cloud_upload",word("Upload your versions","Push"),word("Put recorded versions on the connected server so teammates can get them.","Push local commits to the upstream branch."),"git push"],
      ["download",word("Get everyone’s work","Pull"),word("Download your teammates’ versions and add them to your project.","Fetch and integrate commits from the upstream branch."),"git pull"],
      ["restore",word("Return to an earlier version","Restore"),word("Choose a recorded version when you need to recover something that used to work.","Restore files or reset the branch to an earlier commit."),"git restore"]
    ];
    const faqs=t?[["Do commits require a connection?","No. Commits, diffs, branches, and history work locally. Fetch, pull, and push need access to the remote."],["What happens when work conflicts?","Git stops instead of silently overwriting either side. WinT shows both versions side by side and asks which complete file to keep."],["How often should I commit?","Commit whenever you reach a useful, understandable step. Small focused commits are easier to review and restore."],["Are unpushed commits backed up?","No. They still exist only on this computer until pushed, and a remote is not necessarily a separate backup."]]:[["Do I need to be online?","Only when uploading versions or getting your teammates’ work. Recording versions and looking through them works without a connection."],["Can someone’s work disappear?","The app will not quietly choose. If you both change the same part, it shows both versions and asks which complete version to keep."],["How often should I record a version?","Whenever you reach a useful point that works. Frequent versions make it much easier to recover from a mistake."],["Is a recorded version backed up?","Not yet. It remains on this computer until you upload it, and even an uploaded copy is not guaranteed to be a separate backup."]];
    const place=(title,items,kind)=>`<section class="git-how-place ${kind}"><header>${icon(kind==="shared"?"cloud":"computer")}<strong>${title}</strong></header>${items.map((x,i)=>`<p><i>${i+1}</i><span><strong>${x[0]}</strong><small>${x[1]}</small></span></p>`).join("")}</section>`;
    return `<div class="git-how-page"><div class="git-how-top"><button data-git-help>${icon("arrow_back")}${S.path?word("Back to versions","Back to repository"):word("Back to projects","Back to repositories")}</button><span><h2>${word("How versions work","How Git works")}</h2><p>${word("A five-minute tour. No jargon and nothing to memorise.","A quick guide to the working tree, commits, remotes, and collaboration.")}</p></span><button class="git-terms-toggle" data-git-terms>${icon(t?"toggle_on":"toggle_off")}${t?"Use simple words":"Use Git terms"}</button></div>
      <section class="git-how-intro"><strong>${word("The one-sentence version","The short version")}</strong><p>${word("You work in a folder on your computer. Every so often you record a version — a snapshot you can return to. When you’re ready, you upload those versions so teammates can get them, and download the versions they upload.","You edit a working tree, stage changes, and create commits on a branch. Push commits to an upstream remote and pull commits created by collaborators.")}</p></section>
      <div class="git-how-flow">${place(word("Your computer","Your working copy"),[[word("Changes you are making","Working tree changes"),word("Not recorded or uploaded yet","Uncommitted")],[word("Recorded versions","Local commits"),word("Still on this computer until uploaded","Ahead of upstream")]],"mine")}<div class="git-how-arrows"><span>${icon("east")}<b>${word("Upload","Push")}</b><code>git push</code></span><span>${icon("west")}<b>${word("Download","Pull")}</b><code>git pull</code></span></div>${place(word("The shared copy","Remote repository"),[[word("Your uploaded versions","Pushed commits"),word("Available to your team","Reachable from upstream")],[word("Your teammates’ versions","Remote commits"),word("Ready for you to download","Your branch is behind")]],"shared")}</div>
      <div class="git-how-teammate">${icon("group")}<span><strong>${word("Your teammates do the same thing","Collaborators follow the same workflow")}</strong><small>${word("They record their work, upload it, and download yours. Everyone adds to one shared history.","They commit on branches, push to the remote, and pull your commits into their work.")}</small></span></div>
      <section class="git-how-section"><h3>${word("Four things you’ll actually do","Four core Git operations")}</h3><div class="git-how-actions">${actions.map(a=>`<article>${icon(a[0])}<strong>${a[1]}</strong><p>${a[2]}</p><code>${a[3]}</code></article>`).join("")}</div></section>
      <section class="git-how-section"><h3>${word("Questions people ask on day one","Common questions")}</h3><div class="git-how-faqs">${faqs.map(q=>`<article>${icon("help")}<span><strong>${q[0]}</strong><p>${q[1]}</p></span></article>`).join("")}</div></section>
      <div class="git-how-ready">${icon("history")}<span><strong>${word("That’s it — you’re ready","Ready to use Git")}</strong><small>${word("Describe what changed and record a version whenever you reach a useful point.","Stage the relevant changes, write a focused commit message, then push when ready to share.")}</small></span><button data-git-help>${icon("arrow_forward")}${S.path?word("Go to versions","Go to repository"):word("Choose a project","Choose a repository")}</button></div></div>`;
  }
  function normalizeFriendlyTerms(){if(S.technical||!S.body)return;const swaps=[["Use Git terms","Show Git terms"],["Show the real Git names","Show Git terms"],["These file changes only exist in this working folder.","You have unsaved changes."],["They have not been recorded as a version and have not been uploaded anywhere else.","They are only on this computer and have not been uploaded."],["They are recorded in the version history on this computer, but have not been uploaded anywhere else.","They are saved on this computer, but have not been uploaded."],["Recorded versions have been uploaded to the connected server. This does not guarantee a separate backup.","Your versions have been uploaded."],["Recorded versions exist only on this computer until you connect this project to somewhere else.","Your versions are saved on this computer. Connect this project when you want to upload them."],["One shared copy of the project that nobody edits directly. Everyone uploads versions here, and they join one shared history. It lets the team exchange work; it is not guaranteed to be a separate backup.","One shared copy of the project that nobody edits directly. Everyone uploads versions here, and they join one shared history."],["No. It remains only on this computer until uploaded, and an uploaded copy is not guaranteed to be a separate backup.","Saving keeps it on this computer. Upload it when you want a copy somewhere else."],["uploaded to the remote","uploaded"],["No textual preview for this file.","This file does not have a text preview."],["No versioned projects found","No projects with version history found"],["Recorded versions","Your versions"],["Upload to the team","Upload"],["Upload versions","Upload"],["Get teammates’ work","Download"],["Get team’s work","Download"],["Get the team’s work","Download"],["You have all your teammates’ work","Teammates’ work is up to date"],["Go back in time","Restore a version"],["Recording","Saving"],["recording","saving"],["Recorded","Saved"],["recorded","saved"],["Record","Save"],["record","save"]];for(const el of S.body.querySelectorAll("*"))for(const node of el.childNodes)if(node.nodeType===Node.TEXT_NODE){let value=node.nodeValue;for(const [from,to] of swaps)value=value.replaceAll(from,to);value=value.replace(/^(Share) (\d*) ?(version|versions)$/,"Upload $2 $3").replace(/(\d+) saved (version|versions) from your teammates/,"Teammates’ work · $1 new $2");node.nodeValue=value}}
  function finishBranchMenu(){normalizeFriendlyTerms();const picker=S.body?.querySelector(".git-branch-picker"),menu=picker?.querySelector(".git-branch-menu");if(!picker)return;const current=picker.querySelector(":scope>button strong");if(current&&!S.technical&&!current.textContent.endsWith(" folder"))current.textContent+=` folder`;if(!menu)return;const g=S.data?.info||{},branches=g.branches||[],label=n=>S.technical?n:`${n} folder`;menu.innerHTML=`<header><span>${icon("folder_copy")}<i><strong>${S.technical?"Branches":"Folders"}</strong><small>${S.technical?"Switch, create, or delete local branches":"Choose where to work, or make a new folder"}</small></i></span><button type="button" data-git-branches>${icon("close")}</button></header><div class="git-folder-list">${branches.map(b=>`<div class="git-folder-row ${b===g.branch?"on":""}"><button type="button" data-git-checkout="${esc(b)}">${icon(b===g.branch?"radio_button_checked":"folder")}<span><strong>${esc(label(b))}</strong><small>${b===g.branch?(S.technical?"HEAD":"working here now"):(S.technical?"checkout":"open this folder")}</small></span></button><button type="button" class="git-folder-delete" data-git-delete="${esc(b)}" ${b===g.branch?"disabled":""} title="${b===g.branch?(S.technical?"You cannot delete the checked-out branch":"You cannot delete the folder you are working in"):(S.technical?"Delete branch":"Delete folder")}">${icon("delete")}</button></div>`).join("")}</div><form class="git-new-branch"><strong>${S.technical?"Create a branch":"Create a folder"}</strong><label>${S.technical?"Branch name":"Folder name"}<input name="branch" required autocomplete="off" spellcheck="false" placeholder="${S.technical?"feature-name":"new-folder"}"></label><label>${S.technical?"Start point":"Which folder should it copy?"}<select name="source"><option value="">${S.technical?"None — orphan branch":"None — start empty"}</option>${branches.map(b=>`<option value="${esc(b)}" ${b===g.branch?"selected":""}>${esc(label(b))}</option>`).join("")}</select></label><button>${icon("add")}${S.technical?"Create branch":"Create folder"}</button><small>${S.technical?"Creates and checks out the new branch.":"The new folder opens immediately after it is created."}</small></form>`}
  function finishRepoButton(){const head=S.root?.querySelector(".git-head"),back=head?.querySelector(".tool-back");if(!head||!back)return;let button=head.querySelector(".git-header-repo");if(!button){button=document.createElement("button");button.className="git-header-repo";button.dataset.gitChoose="";back.insertAdjacentElement("afterend",button)}button.innerHTML=`${icon("folder_code")}<span><small>${S.technical?"Repository":"Project"}</small><strong>${esc(S.path?S.name:(S.technical?"Choose repository":"Choose project"))}</strong></span>${icon("unfold_more")}`}
  function polishCleanState(){const g=S.data?.info;if(S.technical||!g||g.changed?.length||g.ahead||!g.remote||!g.upstream)return;const hero=S.body?.querySelector(".sp-hero");if(!hero)return;hero.querySelector("h2").textContent="Everything is up to date.";hero.querySelector("p").textContent="There are no unsaved changes or versions waiting to upload."}
  function polishHelpLanguage(){if(S.technical||!S.help)return;const intro=S.body?.querySelector(".hw-intro");if(!intro)return;intro.querySelector("h3").textContent="The basic idea";intro.querySelector("p").textContent="Your project is a folder on your computer. You change files inside it, then save a version when the folder is in a useful state. Upload sends that saved folder to the team’s copy. Download brings your teammates’ work into your folder.";const set=(selector,text)=>{const el=S.body.querySelector(selector);if(el)el.textContent=text};set(".hw-machine.you>header strong","Your folder");set(".hw-machine.teammate>header strong","Your teammate’s folder");set(".hw-machine.you .hw-step b","Step 1 — save the folder as a version");set(".hw-transfer>span:first-child b","Step 2 — upload the folder");set(".hw-transfer>span:last-child b","Step 4 — download into your folder");set(".hw-machine.shared .hw-copy","The team’s copy of the folder. Upload puts your saved folder here. Download brings the newest team copy back into the folder on your computer.");set(".hw-machine.teammate>.hw-copy","Your teammate changes their own folder, saves versions, uploads, and downloads just like you.");const cards=S.body.querySelectorAll(".git-how-actions article");const copy=[["Save a version","Save your whole folder as it looks right now, with a short description of what changed."],["Upload","Send your saved folder to the team’s copy."],["Download","Bring your teammates’ work into the folder on your computer."],["Restore a version","Make your folder look like an earlier saved version again."]];cards.forEach((card,i)=>{if(!copy[i])return;card.querySelector("strong").textContent=copy[i][0];card.querySelector("p").textContent=copy[i][1]});set(".git-how-ready strong","That’s it — your folder is ready");set(".git-how-ready small","Open your folder, describe what changed, and save a version whenever it reaches a useful point.")}
  function finishFoldersPanel(){normalizeFriendlyTerms();const picker=S.body?.querySelector(".git-branch-picker"),menu=picker?.querySelector(".git-branch-menu");if(!picker)return;const current=picker.firstElementChild?.querySelector("strong");if(current&&!S.technical&&!current.textContent.endsWith(" folder"))current.textContent+=` folder`;if(!menu)return;const g=S.data?.info||{},branches=[...new Set([g.branch,...(g.branches||[])].filter(Boolean))],label=n=>S.technical?n:`${n} folder`;menu.innerHTML=`<header><span>${icon("folder_copy")}<i><strong>${S.technical?"Branches":"Folders"}</strong><small>${S.technical?"Switch, create, or delete local branches":"Choose where to work, or make a new folder"}</small></i></span><button type="button" data-git-branches>${icon("close")}</button></header><div class="git-folder-list">${branches.map(b=>`<div class="git-folder-row ${b===g.branch?"on":""}"><button type="button" data-git-checkout="${esc(b)}">${icon(b===g.branch?"radio_button_checked":"folder")}<span><strong>${esc(label(b))}</strong><small>${b===g.branch?(S.technical?"HEAD":"working here now"):(S.technical?"checkout":"open this folder")}</small></span></button><button type="button" class="git-folder-delete" data-git-delete="${esc(b)}" ${b===g.branch?"disabled":""}>${icon("delete")}</button></div>`).join("")||`<div class="git-folder-empty">${icon("folder_off")}<span><strong>${S.technical?"No local branches found":"No folders found"}</strong><small>${S.technical?"Create a branch below.":"Create a folder below."}</small></span></div>`}</div><form class="git-new-branch"><strong>${S.technical?"Create a branch":"Create a folder"}</strong><label>${S.technical?"Branch name":"Folder name"}<input name="branch" required autocomplete="off" spellcheck="false" placeholder="${S.technical?"feature-name":"new-folder"}"></label><label>${S.technical?"Start point":"Which folder should it copy?"}<select name="source"><option value="">${S.technical?"None — orphan branch":"None — start empty"}</option>${branches.map(b=>`<option value="${esc(b)}" ${b===g.branch?"selected":""}>${esc(label(b))}</option>`).join("")}</select></label><button>${icon("add")}${S.technical?"Create branch":"Create folder"}</button><small>${S.technical?"Creates and checks out the new branch.":"The new folder opens immediately after it is created."}</small></form>`}
  function removeFriendlyFolderHint(){if(S.technical)return;S.body?.querySelector(".git-new-branch>small")?.remove()}
  function finishCommitView(){if(!S.commitView||!S.body)return;const v=S.commitView;S.body.insertAdjacentHTML("beforeend",`<section class="git-commit-view" role="dialog" aria-modal="true"><header>${icon("difference")}<span><small>${S.technical?"Commit":"Saved version"} ${esc(v.hash)}</small><strong>${esc(v.title)}</strong></span><button data-git-close-commit aria-label="Close">${icon("close")}</button></header><div class="git-commit-diff">${v.loading?`<div class="git-commit-loading">${icon("progress_activity")}<span><strong>${S.technical?"Loading commit":"Loading changes"}…</strong><small>${S.technical?"Running git show.":"Reading the files changed in this version."}</small></span></div>`:diffHtml(v.text||"")}</div></section>`)}
  function restoreFileScroll(){const list=S.body?.querySelector(".sp-files");if(list)list.scrollTop=S.filesScroll}
  function installGitHelpAction(){if(S.help||!S.body||S.body.querySelector(".git-content-help"))return;const bar=S.body.querySelector(".sp-repo-bar,.git-picker>header");if(!bar)return;const button=document.createElement("button");button.type="button";button.className="git-how git-content-help";button.dataset.gitHelp="";button.innerHTML=`${icon("help")}${S.technical?"How Git works":"How versions work"}`;const terms=bar.querySelector("[data-git-terms]");bar.insertBefore(button,terms||bar.lastElementChild)}
  function syncLanguage(){if(!S.root)return;const title=S.root.querySelector("[data-git-title]"),sub=S.root.querySelector("[data-git-subtitle]");if(title)title.textContent=S.help?(S.technical?"How Git works":"How folders and versions work"):(S.technical?"Git":"Versions");if(sub)sub.textContent=S.help?(S.technical?"working copies, commits and remotes":"a friendly guide to folders and saved versions"):(S.technical?"commits, branches, remotes and working tree":"save versions on this computer and upload them when ready");queueMicrotask(()=>{installGitHelpAction();finishRepoButton();finishFoldersPanel();removeFriendlyFolderHint();polishCleanState();polishHelpLanguage();finishCommitView();restoreFileScroll()})}
  function render(){if(!S.body)return;syncLanguage();if(S.help)return void(S.body.innerHTML=howItWorks());if(!S.path)return void(S.body.innerHTML=picker());if(!S.data){if(S.error)return void(S.body.innerHTML=`<div class="git-empty error">${icon("error")}<h2>${S.technical?"Could not open repository":"Could not open this project’s version history"}</h2><p>${esc(S.error)}</p><button data-git-choose>${S.technical?"Choose another repository":"Choose another project"}</button></div>`);return void(S.body.innerHTML=`<div class="git-empty">${icon("progress_activity")}<h2>${S.technical?"Opening repository":"Opening version history"}…</h2><p>${S.technical?"Reading status, diff and log.":"Your project is open. Its versions and file changes are loading now."}</p></div>`)}S.body.innerHTML=workspace()}
  function click(e){const pop=e.target.closest("[data-popout-tool]");if(pop)return window.wintShell?.popOutTool?.("git");const pin=e.target.closest("[data-pin-tool]");if(pin)return window.wintShell?.toggleToolPin?.("git");const go=e.target.closest("[data-open-tool]");if(go)return window.wintShell?.openTool?.(go.dataset.openTool);if(e.target.closest("[data-git-terms]")){S.technical=!S.technical;remember();render();return}const pick=e.target.closest("[data-git-open]");if(pick)return open(pick.dataset.gitOpen,pick.dataset.gitName);if(e.target.closest("[data-git-choose]"))return open("","");const resolve=e.target.closest("[data-git-resolve]");if(resolve&&S.selected){const mine=resolve.dataset.gitResolve==="mine",label=mine?(S.technical?"our version":"your version"):"their version";if(confirm(`Keep ${label} for this entire file? The other version will be replaced.`))return act(mine?"keep_mine":"keep_theirs",S.selected)}const skip=e.target.closest("[data-git-skip]");if(skip){const p=skip.dataset.gitSkip;S.excluded.has(p)?S.excluded.delete(p):S.excluded.add(p);render();return}const file=e.target.closest("[data-git-file]");if(file){S.selected=file.dataset.gitFile;render();return}const action=e.target.closest("[data-git-act]");if(action)return act(action.dataset.gitAct);if(e.target.closest("[data-git-discard-all]")&&confirm(S.technical?"Discard all unstaged tracked changes? This cannot be undone.":"Undo every file change shown here? This cannot be undone."))return act("discard_all");const point=e.target.closest("[data-git-point]");if(point){S.openPoint=S.openPoint===point.dataset.gitPoint?"":point.dataset.gitPoint;render();return}const see=e.target.closest("[data-git-see]");if(see){S.notice=`${S.technical?"Commit":"Saved version"} ${see.dataset.gitSee} — ${S.data.history.find(c=>c.hash===see.dataset.gitSee)?.subject||""}`;render();return}const restore=e.target.closest("[data-git-restore]");if(restore&&confirm(S.technical?"Hard reset to this commit? Current tracked changes will be discarded.":"Restore this earlier version? Your current file changes will be undone."))act("restore",restore.dataset.gitRestore)}
  function helpClick(e){if(!e.target.closest("[data-git-help]"))return;S.help=!S.help;render()}
  function commitClick(e){const file=e.target.closest("[data-git-file]");if(file)S.filesScroll=file.closest(".sp-files")?.scrollTop||0;if(e.target.closest("[data-git-close-commit]")){S.commitView=null;render();return}const button=e.target.closest("[data-git-see]");if(button)showCommit(button.dataset.gitSee)}
  function branchClick(e){const remove=e.target.closest("[data-git-delete]");if(remove){const name=remove.dataset.gitDelete;if(confirm(S.technical?`Delete branch ${name}? Unmerged commits may be lost.`:`Delete ${name} folder? Versions that exist only there may be lost.`))act("delete_branch",name);return}const toggle=e.target.closest("[data-git-branches]");if(toggle){S.branchMenu=!S.branchMenu;render();return}const branch=e.target.closest("[data-git-checkout]");if(!branch)return;const name=branch.dataset.gitCheckout;S.branchMenu=false;if(name===S.data?.info?.branch){render();return}act("checkout",name)}
  function submit(e){if(e.target.matches(".git-new-branch")){e.preventDefault();const form=new FormData(e.target),name=String(form.get("branch")||"").trim(),source=String(form.get("source")||"");if(name)act("create_branch_from",`${name}\n${source}`);return}if(!e.target.matches(".sp-save"))return;e.preventDefault();savePoint(new FormData(e.target).get("message"))}
  // `busy` is never saved. It describes a git_workspace call that was in
  // flight in a webview that no longer exists, and opened() skips its load
  // while it is set - so a save that happened mid-load stranded the tool on
  // "Opening version history…" forever, and the next save wrote the same flag
  // straight back. Restoring it false makes the load happen again instead.
  function exportState(){return {path:S.path,name:S.name,repositories:S.repositories,data:S.data,error:S.error,notice:S.notice,selected:S.selected,excluded:[...S.excluded],openPoint:S.openPoint,technical:S.technical};}
  function importState(state){if(!state)return;Object.assign(S,state,{busy:false,excluded:new Set(state.excluded||[]),root:S.root,body:S.body});remember();render();}
  window.wintGit={mount,opened,open,refresh:load,setRepositories,exportState,importState};
})();
